<?php

namespace common\models;

use common\models\base\BusinessProfile;
use tests\codeception\common\fixtures\BusinessProfileFixture;
use tests\codeception\common\unit\DbTestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-19 at 09:45:33.
 */
class BusinessProfileSearchTest extends DbTestCase
{
    /* @var BusinessProfileSearch */
    protected $object;

    /**
     * @inheritdoc
     */
    public function fixtures()
    {
        return [
            'user' => [
                'class' => BusinessProfileFixture::className(),
            ],
        ];
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->object = new BusinessProfileSearch();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }


    /**
     * Business profile search test
     * 
     * @covers common\models\BusinessProfileSearch::search
     */
    public function testSearch()
    {
        $params = [ 
            $this->object->formName() =>[
              'name'=> 'FILE3'
            ]
        ];
        $this->assertNotNull($dp = $this->object->search($params));
        $this->assertEquals(1, $dp->getCount());
        $this->assertEquals('BPROFILE3',$dp->getModels()[0]->name);
    }

    /**
     * @covers common\models\BusinessProfileSearch::getBusinessProfileList
     */
    public function testGetBusinessProfileList()
    {
        $this->assertEquals('{"more":false,"results":[{"id":"1","text":"BPROFILE1"},{"id":"2","text":"BPROFILE2"},{"id":"3","text":"BPROFILE3"},{"id":"4","text":"BPROFILE4"},{"id":"5","text":"BPROFILE5"}]}',
            $this->object->getBusinessProfileList(''));
        $this->assertEquals('{"more":false,"results":[{"id":"1","text":"BPROFILE1"}]}',
            $this->object->getBusinessProfileList('FILE1'));
        $this->assertEquals('{"more":false,"results":{"id":5,"text":"BPROFILE5"}}',
            $this->object->getBusinessProfileList(null,5));
    }
}