<?php

namespace common\models;

use tests\codeception\common\fixtures\CategoryFixture;
use tests\codeception\common\fixtures\EmployeeFixture;
use tests\codeception\common\fixtures\EmployeeSkillFixture;
use tests\codeception\common\fixtures\SkillFixture;
use tests\codeception\common\fixtures\SkillLevelFixture;
use tests\codeception\common\fixtures\UserFixture;
use tests\codeception\common\unit\DbTestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-16 at 15:55:47.
 */
class SkillSearchTest extends DbTestCase
{
    /**
     * @inheritdoc
     */
    public function fixtures()
    {
        return [
            'user' => [
                'class' => UserFixture::className(),
                'dataFile' => '@tests/codeception/common/fixtures/data/user.php'
            ],
            'employee' => [
                'class' => EmployeeFixture::className(),
                'dataFile' => '@tests/codeception/common/fixtures/data/employee.php'
            ],
            'category' => [
                'class' => CategoryFixture::className(),
                'dataFile' => '@tests/codeception/common/fixtures/data/category.php'
            ],
            'level' => [
                'class' => SkillLevelFixture::className(),
                'dataFile' => '@tests/codeception/common/fixtures/data/skill_level.php'
            ],
            'skill' => [
                'class' => SkillFixture::className(),
                'dataFile' => '@tests/codeception/common/fixtures/data/skill.php'
            ],
            'employee_skill' => [
                'class' => EmployeeSkillFixture::className(),
                'dataFile' => '@tests/codeception/common/fixtures/data/employee_skill.php'
            ],
        ];
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }


    /**
     * @covers common\models\SkillSearch::search
     * @todo   Implement testSearch().
     */
    public function testSearch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers common\models\SkillSearch::getUnassignedSkillsQuery
     */
    public function testGetUnassignedSkillsQuery()
    {
        $search = new SkillSearch();

        $q1 = $search->getUnassignedSkillsQuery(1);
        $this->assertEquals(0, $q1->count());

        $q1 = $search->getUnassignedSkillsQuery(2);
        $this->assertEquals(5, $q1->count());

        $q1 = $search->getUnassignedSkillsQuery(3);
        $this->assertEquals(10, $q1->count());

        $q1 = $search->getUnassignedSkillsQuery(4);
        $this->assertEquals(10, $q1->count());

        $q1 = $search->getUnassignedSkillsQuery(5);
        $this->assertEquals(15, $q1->count());

    }
}