<?php

namespace common\models;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-31 at 12:45:39.
 */
class UserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new User;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers common\models\User::tableName
     * @todo   Implement testTableName().
     */
    public function testTableName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers common\models\User::behaviors
     * @todo   Implement testBehaviors().
     */
    public function testBehaviors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers common\models\User::rules
     * @todo   Implement testRules().
     */
    public function testRules()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers common\models\User::findIdentity
     * @todo   Implement testFindIdentity().
     */
    public function testFindIdentity()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers common\models\User::findIdentityByAccessToken
     * @todo   Implement testFindIdentityByAccessToken().
     */
    public function testFindIdentityByAccessToken()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers common\models\User::findByUsername
     * @todo   Implement testFindByUsername().
     */
    public function testFindByUsername()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers common\models\User::findByPasswordResetToken
     * @todo   Implement testFindByPasswordResetToken().
     */
    public function testFindByPasswordResetToken()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers common\models\User::isPasswordResetTokenValid
     * @todo   Implement testIsPasswordResetTokenValid().
     */
    public function testIsPasswordResetTokenValid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers common\models\User::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers common\models\User::getAuthKey
     * @todo   Implement testGetAuthKey().
     */
    public function testGetAuthKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers common\models\User::validateAuthKey
     * @todo   Implement testValidateAuthKey().
     */
    public function testValidateAuthKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers common\models\User::validatePassword
     * @todo   Implement testValidatePassword().
     */
    public function testValidatePassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers common\models\User::setPassword
     * @todo   Implement testSetPassword().
     */
    public function testSetPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers common\models\User::generateAuthKey
     * @todo   Implement testGenerateAuthKey().
     */
    public function testGenerateAuthKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers common\models\User::generatePasswordResetToken
     * @todo   Implement testGeneratePasswordResetToken().
     */
    public function testGeneratePasswordResetToken()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers common\models\User::removePasswordResetToken
     * @todo   Implement testRemovePasswordResetToken().
     */
    public function testRemovePasswordResetToken()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers common\models\User::checkPasswordPolicy
     * @todo   Implement testCheckPasswordPolicy().
     */
    public function testCheckPasswordPolicy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}