<?php

namespace common\models;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-31 at 12:45:39.
 */
class UserTest extends \tests\codeception\common\unit\DbTestCase
{
    /**
     * @var User
     */
    protected $object;

    public $actor = false;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->object = new User;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }


}