<?php

namespace console\controllers;

use tests\codeception\common\fixtures\CategoryFixture;
use tests\codeception\common\fixtures\EmployeeFixture;
use tests\codeception\common\fixtures\EmployeeSkillFixture;
use tests\codeception\common\fixtures\SkillFixture;
use tests\codeception\common\fixtures\SkillLevelFixture;
use tests\codeception\common\fixtures\UserFixture;
use tests\codeception\console\unit\DbTestCase;
use Yii;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-16 at 13:06:25.
 */
class MailControllerTest extends DbTestCase
{

    /**
     * @inheritdoc
     */
    public function fixtures()
    {
        return [
            'user' => [
                'class' => UserFixture::className(),
                'dataFile' => '@tests/codeception/common/fixtures/data/user.php'
            ],
            'employee' => [
                'class' => EmployeeFixture::className(),
                'dataFile' => '@tests/codeception/common/fixtures/data/employee.php'
            ],
            'category' => [
                'class' => CategoryFixture::className(),
                'dataFile' => '@tests/codeception/common/fixtures/data/category.php'
            ],
            'level' => [
                'class' => SkillLevelFixture::className(),
                'dataFile' => '@tests/codeception/common/fixtures/data/skill_level.php'
            ],
            'skill' => [
                'class' => SkillFixture::className(),
                'dataFile' => '@tests/codeception/common/fixtures/data/skill.php'
            ],
            'employee_skill' => [
                'class' => EmployeeSkillFixture::className(),
                'dataFile' => '@tests/codeception/common/fixtures/data/employee_skill.php'
            ],
        ];
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->mockApplication();
        Yii::$classMap['yii\helpers\Console'] = __DIR__.'/Console.php';

        $this->unloadFixtures();
        $this->loadFixtures();

        Yii::$app->mailer->fileTransportCallback = function ($mailer, $message) {
            return 'testing_message.eml';
        };

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->destroyApplication();
        @unlink($this->getMessageFile());
    }

    /**
     * @covers console\controllers\MailController::actionUnassignedSkills
     */
    public function testActionUnassignedSkills()
    {
        $this->expectOutputRegex('/user2 BBAACC/');
        $this->assertEquals(0,Yii::$app->runAction('mail/unassigned-skills', []));
    }

    /**
     * @covers console\controllers\MailController::actionUnassignedSkills
     */
    public function testActionUnassignedSkillsX()
    {
        $this->expectOutputRegex('/End of sending notice to employees. Sent:4/');
        $this->assertEquals(0,Yii::$app->runAction('mail/unassigned-skills', []));
    }

    /**
     * @covers console\controllers\MailController::actionUnassignedSkills
     */
    public function testActionUnassignedSkills1()
    {
        $this->assertEquals(0,Yii::$app->runAction('mail/unassigned-skills', []));
        echo $this->getMessageFile();
    }

    /**
     * @covers console\controllers\MailController::actionUnassignedSkills
     */
    private function getMessageFile()
    {
        return Yii::getAlias(Yii::$app->mailer->fileTransportPath) . '/testing_message.eml';
    }
 
}


