<?php

namespace jk\sys;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-01 at 19:53:02.
 */
class LogConsoleTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var LogConsole
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new LogConsole;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers jk\sys\LogConsole::log
     * @todo   Implement testLog().
     */
    public function testLog()
    {
        $this->expectOutputRegex('/TestMessage1$/');
        $this->object->log('TestMessage1');
    }
}