<?php

namespace jk\sys;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-01-31 at 09:07:58.
 */
class PropertiesTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Properties
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Properties;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers jk\sys\Properties::setValues
     */
    public function testSetValues()
    {
        $this->assertEquals('AAA', $this->object->getProperty('prop1', 'AAA'));
        $this->assertNull($this->object->getProperty('prop1'));
        $this->object->setValues(['prop1' => 'test1']);
        $this->assertEquals('test1', $this->object->getProperty('prop1'));
    }

    /**
     * @covers jk\sys\Properties::getProperty
     */
    public function testGetProperty()
    {
        $this->object = new Properties([
            'values' => [
                'prop1' => 'test1'
            ]
        ]);
        $this->assertEquals('test1', $this->object->getProperty('prop1'));
        $this->assertEquals('test1', $this->object->getProperty('prop1', 'AAA'));
    }
}