<?php

namespace jk\util;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-03 at 22:49:58.
 */
class SkillsHelperTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SkillsHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers jk\sys\SkillsHelper::getYearsList
     */
    public function testGetYearsList()
    {
        $this->assertContains(2011,SkillsHelper::getYearsList());
        $this->assertContains(2012,SkillsHelper::getYearsList());
        $this->assertContains(2013,SkillsHelper::getYearsList());
    }

    /**
     * @covers jk\sys\SkillsHelper::getDurationList
     */
    public function testGetDurationList()
    {
        $this->assertContains(0.50,SkillsHelper::getDurationList());
        $this->assertContains(20.50,SkillsHelper::getDurationList());
    }
}